
// import { SideNavbar } from "@/app/_shared/components/sidemenu/SideNavbar"
import '../globals.css';


export const metadata = {
  title: 'Aidit',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div lang="en">
      <div className="dashbord flex bg-[#5A8D7D]">
        {children}
      </div>
    </div>
  )
}
